---
title: "Gov 50 Final Project"
author: "Faith Oji"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Milestone One

Honestly, I'm not exactly sure what I want my final project to be about quite yet. I have a lot of interests in the lasting effects of slavery on systematic racism in the united states, as well as how family histories (in relation to the Slave Trade) influence political activity today. I'm not yet sure, though, about how I would tie this in to my final project. I'd also be interested in how immigration rates affect different aspects in our system. I also potentially could do a project on the prison systems and abolition. I'm just not sure yet what direction I want to go in or how I'd go in that direction.

## Milestone Two

Upon further research, I've decided to completely change the course of my project. I've decided, instead, to do a project surrounding marriage, specifically pulling from a data set in relation to a study called 'Marriage is Not Dead'. My research question is whether or not race has an impact on tendency towards marriage. My hypothesis is that, throughout the years, Black People in America will have the highest proportion of individuals that have never been married. This hypothesis stems from a few points, with the main one being the effect of systematic racism in the United States. It's common knowledge that marriage is very expensive. However, the systems within this country make it disproportionately harder for Black People to acquire and maintain large amounts of wealth, and as such, they would be less likely to take on the financial burden of a wedding. There is also the factor of the prison systems breaking up Black families, which would also contribute to a lower marriage rate. 

My explanatory variables of interest are 'White', 'Black', and 'Hisp', which represent White People, Black or African-American People, and Hispanic People, respectively. These are all different races. The outcome variable of interest would be the proportion of the population that is unmarried per year. This was measured through the survey data, and the trend could be noted through a line graph. An observed pattern in the data that would support this hypothesis would be whether or not the proportion of unmarried Black People was significantly higher than the other races, as well as the overall proportion of unmarried individuals throughout the years. My hypothesis would be disproved if the proportions were similar amongst all the populations, or if a different race had a significantly higher proportion of unmarried individuals. 